plugins {
    alias libs.plugins.fabricLoom apply(false)
    alias libs.plugins.neoModDev apply(false)
    alias libs.plugins.curseForge apply(false)
    alias libs.plugins.modrinth apply(false)
}

subprojects {
    configurations.configureEach {
        resolutionStrategy {
            cacheChangingModulesFor 60, 'seconds'
            cacheDynamicVersionsFor 60, 'seconds'
        }
    }
}
