repositories {
    // For JourneyMap
    maven {
        url = "https://jm.gserv.me/repository/maven-public/"
    }
}

dependencies {
    compileOnly group: 'info.journeymap', name: 'journeymap-api', version: project.journeymap_api_forge_version, changing: true
    //runtimeOnly "curse.maven:journeymap-${project.journeymap_project_id}:${project.journeymap_forge_file_id}"
    modImplementation "net.blay09.mods:unbreakables-common:${unbreakables_version}"
}
