dependencies {
    implementation(libs.balmCommon) {
        changing = libs.versions.balm.get().endsWith("SNAPSHOT")
    }
    accessTransformers(libs.balmCommon)
    compileOnly(libs.journeyMapApiCommon)
    compileOnly(libs.blueMap)
    compileOnly(libs.dynmap)
    compileOnly(libs.unbreakablesCommon)
}