modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="waystones"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
logoFile="waystones.png"
credits="${credits}"
authors="${mod_author}"
description='''${description}'''
[[mixins]]
config = "waystones.mixins.json"
[[mixins]]
config = "waystones.neoforge.mixins.json"
[[dependencies.waystones]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.waystones]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.waystones]]
modId="balm"
type="required"
versionRange="[${balm_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.waystones]]
modId="shogi"
type="required"
versionRange="[${shogi_version},)"
ordering="NONE"
side="BOTH"
